// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOMSvsha7CVx4Mj3a5N0T35M0FOxp7t-M',
    appId: '1:556302801820:web:bff80b43a30f4e32f20659',
    messagingSenderId: '556302801820',
    projectId: 'anasyd-movieapp',
    authDomain: 'anasyd-movieapp.firebaseapp.com',
    storageBucket: 'anasyd-movieapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ1_GnRa4MrZ5ZvPbuXVFJRP2Hy2XDD4Y',
    appId: '1:556302801820:android:9f60d422579b4621f20659',
    messagingSenderId: '556302801820',
    projectId: 'anasyd-movieapp',
    storageBucket: 'anasyd-movieapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFymDV5AQD396fQZau_mHqI6_H5_77FGY',
    appId: '1:556302801820:ios:a730b3ce73f72409f20659',
    messagingSenderId: '556302801820',
    projectId: 'anasyd-movieapp',
    storageBucket: 'anasyd-movieapp.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFymDV5AQD396fQZau_mHqI6_H5_77FGY',
    appId: '1:556302801820:ios:b7ade909a77cdc01f20659',
    messagingSenderId: '556302801820',
    projectId: 'anasyd-movieapp',
    storageBucket: 'anasyd-movieapp.appspot.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
